### PR TITLE
Add Gaussian Elimination

### PR DESCRIPTION
**Pull request by antonAce**
Another option for an algorithm of Gaussian Elimination with solution checking algorithm, based on Rouché–Capelli theorem.

### CODE REVIEW

**Comment by xennygrimmato** [comment]
@antonAce Sorry I missed this. Due you mind re-opening the PR? I'd be happy to merge it.

**Comment by antonAce** [comment]
Sure, that'd be great!

**Comment by antonAce** [comment]
Thx

**Comment by xennygrimmato** [comment]
Cool, you'll have to reopen the pull request as I don't have permission to do it.

**Comment by antonAce** [comment]
Reopened in PR #86

**Pull request closed without merging**
